'*********************************************************************************************
' carep: SyncroSim Base Package for simulating the energy and protein dynamics of caribou.
'
' Copyright © 2007-2019 Apex Resource Management Solution Ltd. (ApexRMS). All rights reserved.
'
'*********************************************************************************************

Imports SyncroSim.Core

Partial Class CAREPTransformer

    Private ABYFI As New MVPlant("ABYFI")
    Private ACCDFI As New MVPlant("ACCDFI")
    Private ACCFI As New MVPlant("ACCFI")
    Private ACCPOOL As New MVHour("ACCPOOL")
    Private ACWDFI As New MVPlant("ACWDFI")
    Private ACWFI As New MVPlant("ACWFI")
    Private ACWPOOL As New MVHour("ACWPOOL")
    Private ADF As New MVStratumPlantTime("ADF")
    Private AFI As New MVPlant("AFI")
    Private ANDFI As New MVPlant("ANDFI")
    Private ANDPOOL As New MVHour("ANDPOOL")
    Private AR As New MVStratumPlant("AR")
    Private ATPOOL As New MVHour("ATPOOL")
    Private BSA As New MVStratumPlantTime("BSA")
    Private BYFEC As New MVPlantTime("BYFEC")
    Private BYFECHR As New MVPlantHour("BYFECHR")
    Private BYFI As New MVPlantTime("BYFI")
    Private BYFIHR As New MVPlantHour("BYFIHR")
    Private BYMEI As New MVPlantTime("BYMEI")
    Private BYMEIHR As New MVPlantHour("BYMEIHR")
    Private BYMNI As New MVPlantTime("BYMNI")
    Private BYMNIHR As New MVPlantHour("BYMNIHR")
    Private BYNFEC As New MVPlantTime("BYNFEC")
    Private BYNFECHR As New MVPlantHour("BYNFECHR")
    Private BYNI As New MVPlantTime("BYNI")
    Private BYNIHR As New MVPlantHour("BYNIHR")
    Private CCDFI As New MVPlantTime("CCDFI")
    Private CCDFIHR As New MVPlantHour("CCDFIHR")
    Private CCDNI As New MVPlantTime("CCDNI")
    Private CCDNIHR As New MVPlantHour("CCDNIHR")
    Private CCFEC As New MVPlantTime("CCFEC")
    Private CCFECHR As New MVPlantHour("CCFECHR")
    Private CCMEI As New MVPlantTime("CCMEI")
    Private CCMEIHR As New MVPlantHour("CCMEIHR")
    Private CCMNI As New MVPlantTime("CCMNI")
    Private CCMNIHR As New MVPlantHour("CCMNIHR")
    Private CCNFEC As New MVPlantTime("CCNFEC")
    Private CCNFECHR As New MVPlantHour("CCNFECHR")
    Private CCNI As New MVPlantTime("CCNI")
    Private CCNIHR As New MVPlantHour("CCNIHR")
    Private CCNPL As New MVPlantTime("CCNPL")
    Private CCNPLHR As New MVPlantHour("CCNPLHR")
    Private CCNPRIOR As New MVPlantHour("CCNPRIOR")
    Private CCPOOL As New MVPlantTime("CCPOOL")
    Private CCPOOLHR As New MVPlantHour("CCPOOLHR")
    Private CCPOOLIN As New MVPlant("CCPOOLIN")
    Private CCPRIOR As New MVPlantHour("CCPRIOR")
    Private CWDFI As New MVPlantTime("CWDFI")
    Private CWDFIHR As New MVPlantHour("CWDFIHR")
    Private CWDNI As New MVPlantTime("CWDNI")
    Private CWDNIHR As New MVPlantHour("CWDNIHR")
    Private CWFEC As New MVPlantTime("CWFEC")
    Private CWFECHR As New MVPlantHour("CWFECHR")
    Private CWMEI As New MVPlantTime("CWMEI")
    Private CWMEIHR As New MVPlantHour("CWMEIHR")
    Private CWMNI As New MVPlantTime("CWMNI")
    Private CWMNIHR As New MVPlantHour("CWMNIHR")
    Private CWNFEC As New MVPlantTime("CWNFEC")
    Private CWNDFECHR As New MVPlantHour("CWNDFECHR")
    Private CWNI As New MVPlantTime("CWNI")
    Private CWNIHR As New MVPlantHour("CWNIHR")
    Private CWNPL As New MVPlantTime("CWNPL")
    Private CWNPLHR As New MVPlantHour("CWNPLHR")
    Private CWNPRIOR As New MVPlantHour("CWNPRIOR")
    Private CWPOOL As New MVPlantTime("CWPOOL")
    Private CWPOOLHR As New MVPlantHour("CWPOOLHR")
    Private CWPOOLIN As New MVPlant("CWPOOLIN")
    Private CWPRIOR As New MVPlantHour("CWPRIOR")
    Private AGEOUT As New MVTime("AGE")
    Private CALFFATEOUT As New MVTime("CALFFATE")
    Private DAYSGES As New MVTime("DAYSGES")
    Private DAYSLAC As New MVTime("DAYSLAC")
    Private DFI As New MVPlantTime("DFI")
    Private DIET As New MVStratumPlantTime("DIET")
    Private DPMNI As New MVPlantTime("DPMNI")
    Private DPMNIHR As New MVPlantHour("DPMNIHR")
    Private DPNFEC As New MVPlantTime("DPNFEC")
    Private DPNFECHR As New MVPlantHour("DPNFECHR")
    Private DPNI As New MVPlantTime("DPNI")
    Private DPNIHR As New MVPlantHour("DPNIHR")
    Private DPNPL As New MVPlantTime("DPNPL")
    Private DPNPLHR As New MVPlantHour("DPNPLHR")
    Private DPNPRIOR As New MVPlantHour("DPNPRIOR")
    Private EA As New MVStageTime("EA")
    Private EAFAT As New MVStageTime("EAFAT")
    Private EAINT As New MVStageTime("EAINT")
    Private EANTLCO As Double
    Private EAPRO As New MVStageTime("EAPRO")
    Private EAPRORE As New MVStageTime("EAPRORE")
    Private EB As New MVTime("EB")
    Private EBMRCO As Double
    Private ECONCOAT As Double
    Private ECONFAT As Double
    Private ECONFI As Double
    Private ECONMLK As New MVTime("ECONMLK")
    Private ECONPRO As Double
    Private EDFAT As New MVStageTime("EDFAT")
    Private EDPRO As New MVStageTime("EDPRO")
    Private EFATCHG As New MVTime("EFATCHG")
    Private ENDAYAN As Integer
    Private ENDAYCT As Integer
    Private ENDAYGES As Integer
    Private ENDAYLAC As Integer
    Private ENDAYSC As Integer
    Private ENDAYSUM As Integer
    Private ER As New MVStageTime("ER")
    Private ERACT As New MVTime("ERACT")
    Private ERANTL As New MVTime("ERANTL")
    Private ERBASE As New MVTime("ERBASE")
    Private ERCOAT As New MVTime("ERCOAT")
    Private EREAT As New MVTime("EREAT")
    Private ERFAT As New MVStageTime("ERFAT")
    Private ERFDEP As New MVTime("ERFDEP")
    Private ERFET As New MVTime("ERFET")
    Private ERGES As New MVTime("ERGES")
    Private ERGESFAT As New MVTime("ERGESFAT")
    Private ERINT As New MVStageTime("ERINT")
    Private ERLAC As New MVTime("ERLAC")
    Private ERMA As New MVTime("ERMA")
    Private ERMET As New MVStageTime("ERMET")
    Private ERNP As New MVTime("ERNP")
    Private ERPARA As New MVTime("ERPARA")
    Private ERPAW As New MVTime("ERPAW")
    Private ERPDEP As New MVTime("ERPDEP")
    Private ERPRO As New MVStageTime("ERPRO")
    Private ERRUN As New MVTime("ERRUN")
    Private ERSCRF As New MVTime("ERSCRF")
    Private ERSTD As New MVTime("ERSTD")
    Private ERSUM As New MVTime("ERSUM")
    Private ERTAR As New MVStageTime("ERTAR")
    Private ERWLK As New MVTime("ERWLK")
    Private ESCRFCO As Double
    Private EU As New MVStageTime("EU")
    Private EUFAT As New MVStageTime("EUFAT")
    Private EUINT As New MVStageTime("EUINT")
    Private EUN As New MVTime("EUN")
    Private EUPRO As New MVStageTime("EUPRO")
    Private EUPRORE As New MVStageTime("EUPRORE")
    Private EXCEI As New MVHour("EXCEI")
    Private EXCEISUM As New MVTime("EXCEISUM")
    Private EXCFI As New MVHour("EXCFI")
    Private EXCFISUM As New MVTime("EXCFISUM")
    Private FATCAT As New MVStage("FATCAT")
    Private FATDEP As New MVStage("FATDEP")
    Private FATMOBRT As Double
    Private FB As New MVStratumPlantTime("FB")
    Private FEC As New MVTime("FEC")
    Private FECHR As New MVPlantHour("FECHR")
    Private FECP As New MVPlantTime("FECP")
    Private FI As New MVTime("FI")
    Private FIHR As New MVPlantHour("FIHR")
    Private FIMET As New MVPlantTime("FIMET")
    Private FIP As New MVPlantTime("FIP")
    Private FMMAX As New MVTime("FMMAX")
    Private HP As New MVStageTime("HP")
    Private HPDFAT As New MVStageTime("HPDFAT")
    Private HPDPRO As New MVStageTime("HPDPRO")
    Private HPUFAT As New MVStageTime("HPUFAT")
    Private HPUINT As New MVStageTime("HPUINT")
    Private HPUPRO As New MVStageTime("HPUPRO")
    Private HPUPRORE As New MVStageTime("HPUPRORE")
    Private HREEAT As Double
    Private HRELIE As Double
    Private HREPAW As Double
    Private HRERUN As Double
    Private HRESTD As Double
    Private HREWLK As Double
    Private KEFAT As New MVStage("KEFAT")
    Private KEINT As New MVStage("KEINT")
    Private KEPRO As New MVStage("KEPRO")
    Private KNINT As New MVStage("KNINT")
    Private KNPRO As New MVStage("KNPRO")
    Private KPCC As New MVTime("KPCC")
    Private KPCW As New MVTime("KPCW")
    Private KPND As New MVPlant("KPND")
    Private KPNDMIN As Double
    Private LACT As New MVTime("LACT")
    Private LACTIN As Double
    Private LACTYR As Double
    Private MAXSNODEP As New MVTime("MAXSNODEP")
    Private MAXWTFET As New MVTime("MAXWTFET")
    Private MCDOMMX As New MVHour("MCDOMMX")
    Private MCDOMMXD As New MVTime("MCDOMMXD")
    Private MCMNI As New MVPlantTime("MCMNI")
    Private MCMNIHR As New MVPlantHour("MCMNIHR")
    Private MCNFEC As New MVPlantTime("MCNFEC")
    Private MCNFECHR As New MVPlantHour("MCNFECHR")
    Private MCNIMX As New MVHour("MCNIMX")
    Private MCNIMXD As New MVTime("MCNIMXD")
    Private MCNPL As New MVPlantTime("MCNPL")
    Private MCNPLHR As New MVPlantHour("MCNPLHR")
    Private MCNPRIOR As New MVPlantHour("MCNPRIOR")
    Private MEI As New MVTime("MEI")
    Private MEIHR As New MVPlantHour("MEIHR")
    Private MEIP As New MVPlantTime("MEIP")
    Private MFN As New MVTime("MFN")
    Private MFNCO As Double
    Private MNI As New MVTime("MNI")
    Private MNIHR As New MVPlantHour("MNIHR")
    Private MNIP As New MVPlantTime("MNIP")
    Private MNL As New MVStageTime("MNL")
    Private MPFI As New MVHour("MPFI")
    Private MPFIAVG As New MVTime("MPFIAVG")
    Private NA As New MVStageTime("NA")
    Private NAINT As New MVStageTime("NAINT")
    Private NANTLCO As Double
    Private NAPRO As New MVStageTime("NAPRO")
    Private NAPRORE As New MVStageTime("NAPRORE")
    Private NB As New MVTime("NB")
    Private NCOATCO As Double
    Private NCONPRO As Double
    Private NDF As New MVStratumPlantTime("NDF")
    Private NDFEC As New MVPlantTime("NDFEC")
    Private NDFECHR As New MVPlantHour("NDFECHR")
    Private NDFI As New MVPlantTime("NDFI")
    Private NDFIHR As New MVPlantHour("NDFIHR")
    Private NDNFEC As New MVPlantTime("NDNFEC")
    Private NDNFECHR As New MVPlantHour("NDNFECHR")
    Private NDNI As New MVPlantTime("NDNI")
    Private NDNIHR As New MVPlantHour("NDNIHR")
    Private NDNPL As New MVPlantTime("NDNPL")
    Private NDNPLHR As New MVPlantHour("NDNPLHR")
    Private NDNPRIOR As New MVPlantHour("NDNPRIOR")
    Private NDPOOL As New MVPlantTime("NDPOOL")
    Private NDPOOLHR As New MVPlantHour("NDPOOLHR")
    Private NDPOOLIN As New MVPlant("NDPOOLIN")
    Private NDPRIOR As New MVPlantHour("NDPRIOR")
    Private NDPRO As New MVStageTime("NDPRO")
    Private NEUNCO As Double
    Private NFEC As New MVPlantTime("NFEC")
    Private NFECHR As New MVPlantHour("NFECHR")
    Private NFETCO As Double
    Private NI As New MVPlantTime("NI")
    Private NIHR As New MVPlantHour("NIHR")
    Private NLDPRO As New MVStageTime("NLDPRO")
    Private NLUINT As New MVStageTime("NLUINT")
    Private NLUPRO As New MVStageTime("NLUPRO")
    Private NLUPRORE As New MVStageTime("NLUPRORE")
    Private NPNI As New MVPlantTime("NPNI")
    Private NPNIHR As New MVPlantHour("NPNIHR")
    Private NPNURN As New MVPlantTime("NPNURN")
    Private NPNURNHR As New MVPlantHour("NPNURNHR")
    Private NPROCHG As New MVTime("NPROCHG")
    Private NR As New MVStageTime("NR")
    Private NRTAR As New MVStageTime("NRTAR")
    Private NRACT As New MVTime("NRACT")
    Private NRANTL As New MVTime("NRANTL")
    Private NRBASE As New MVTime("NRBASE")
    Private NRCOAT As New MVTime("NRCOAT")
    Private NRFDEP As New MVTime("NRFDEP")
    Private NRFET As New MVTime("NRFET")
    Private NRGES As New MVTime("NRGES")
    Private NRINT As New MVStageTime("NRINT")
    Private NRLAC As New MVTime("NRLAC")
    Private NRMA As New MVTime("NRMA")
    Private NRMET As New MVStageTime("NRMET")
    Private NRPARA As New MVTime("NRPARA")
    Private NRPDEP As New MVTime("NRPDEP")
    Private NRPRO As New MVStageTime("NRPRO")
    Private NRSCRF As New MVTime("NRSCRF")
    Private NRSUM As New MVTime("NRSUM")
    Private NRUM As New MVTime("NRUM")
    Private NSCRFCO As Double
    Private NU As New MVStageTime("NU")
    Private NUINT As New MVStageTime("NUINT")
    Private NUPRO As New MVStageTime("NUPRO")
    Private NUPRORE As New MVStageTime("NUPRORE")
    Private PBYN As Double
    Private PCC As New MVPlant("PCC")
    Private PCCDIG As New MVPlant("PCCDIG")
    Private PCCDIGIN As New MVPlant("PCCDIGIN")
    Private PCCDNIBY As New MVPlantTime("PCCDNIBY")
    Private PCCIBY As New MVPlantTime("PCCIBY")
    Private PCMAX As New MVStratumPlantTime("PCMAX")
    Private PCONFET As Double
    Private PCONIN As Double
    Private PCONMLK As New MVTime("PCONMLK")
    Private PCWDIG As New MVPlant("PCWDIG")
    Private PCWN As Double
    Private PDEG As New MVStratumPlantTime("PDEG")
    Private PDIG As New MVPlant("PDIG")
    Private PDOM As Double
    Private PDPN As Double
    Private PERTAR As New MVStageTime("PERTAR")
    Private PFAT As New MVTime("PFAT")
    Private PFATDEP As Double
    Private PFATIN As Double
    Private PFATMIN As Double
    Private PFATWAT As Double
    Private PFETFAT As Double
    Private PFIP As New MVPlant("PFIP")
    Private PFOR As New MVStratumLactTime("PFOR")
    Private PFOREAT As New MVStratumLactTime("PFOREAT")
    Private PFORPAW As New MVStratumLactTime("PFORPAW")
    Private PLIE As New MVStratumLactTime("PLIE")
    Private PMCDOM As Double
    Private PMCN As Double
    Private PMCNI As New MVHour("PMCNI")
    Private PMCNIAVG As New MVTime("PMCNIAVG")
    Private PMEBY As Double
    Private PMECC As Double
    Private PMECW As Double
    Private PMMAX As New MVTime("PMMAX")
    Private PMUSPRO As Double
    Private PMUSWAT As Double
    Private PNIT As New MVStratumPlantTime("PNIT")
    Private PNRTAR As New MVStageTime("PNRTAR")
    Private PPRO As New MVTime("PPRO")
    Private PPROIN As Double
    Private PPROMIN As Double
    Private PRCAP As Double
    Private PREG As New MVTime("PREG")
    Private PREGIN As Double
    Private PREGYR As Double
    Private PROCAT As New MVStage("PROCAT")
    Private PRODEP As New MVStage("PRODEP")
    Private PROMOBRT As Double
    Private PRTAR As New MVStageTime("PRTAR")
    Private PRUMDRY As Double
    Private PRUMGUT As Double
    Private PRUN As New MVStratumLactTime("PRUN")
    Private PSTD As New MVStratumLactTime("PSTD")
    Private PTARSUM As New MVTime("PTARSUM")
    Private PTPCW As New MVPlantTime("PTPCW")
    Private PTPCW_XMAX As Double
    Private PTPCW_XMIN As Double
    Private PTPCW_YMAX As Double
    Private PTPCW_YMIN As Double
    Private PTPNDIG As Double
    Private PUPN As Double
    Private PWATIN As Double
    Private PWATMAX As Double
    Private PWLK As New MVStratumLactTime("PWLK")
    Private QM As New MVTime("QM")
    Private RBYFI As New MVPlantHour("RBYFI")
    Private RCAP As New MVTime("RCAP")
    Private RCCDFI As New MVPlantHour("RCCDFI")
    Private RCCPOOL As New MVHour("RCCPOOL")
    Private RCCTAN As New MVPlant("RCCTAN")
    Private RCWDFI As New MVPlantHour("RCWDFI")
    Private RCWPOOL As New MVHour("RCWPOOL")
    Private REI As New MVHour("REI")
    Private RENBY As New MVHour("RENBY")
    Private RENCC As New MVHour("RENCC")
    Private RENCW As New MVHour("RENCW")
    Private RNCCTAN As New MVPlantTime("RNCCTAN")
    Private RNCCTAN_XMAX As Double
    Private RNCCTAN_XMIN As Double
    Private RNCCTAN_YMAX As Double
    Private RNCCTAN_YMIN As Double
    Private RNDFI As New MVPlantHour("RNDFI")
    Private RPFI As New MVHour("RPFI")
    Private RPFIAVG As New MVTime("RPFIAVG")
    Private SDPROP As Double
    Private SINKDEP As New MVTime("SINKDEP")
    Private SNODEP As New MVStratumTime("SNODEP")
    Private SNOWX As New MVTime("SNOWX")
    Private STAGEPR As New MVStageTime("STAGEPR")
    Private STDAYAN As Integer
    Private STDAYCT As Integer
    Private STDAYGES As Integer
    Private STDAYLAC As Integer
    Private STDAYSC As Integer
    Private STDAYSUM As Integer
    Private LOCATION As New MVStratum_ID_Time("StratumID")
    Private TER As New MVTime("TER")
    Private TGRCALF As New MVTime("TGRCALF")
    Private TGRFET As New MVTime("TGRFET")
    Private TMLKPR As New MVTime("TMLKPR")
    Private TMLKPRWT As New MVTime("TMLKPRWT")
    Private TOTDIG As New MVPlantHour("TOTDIG")
    Private TPNI As New MVPlantTime("TPNI")
    Private TPNIHR As New MVPlantHour("TPNIHR")
    Private WTTBIR As Double
    Private WTTMLKPR As Double
    Private TWTCALF As New MVTime("TWTCALF")
    Private TWTFET As New MVTime("TWTFET")
    Private UNL As New MVTime("UNL")
    Private UPMNI As New MVPlantTime("UPMNI")
    Private UPMNIHR As New MVPlantHour("UPMNIHR")
    Private UPNFEC As New MVPlantTime("UPNFEC")
    Private UPNFECHR As New MVPlantHour("UPNFECHR")
    Private UPNI As New MVPlantTime("UPNI")
    Private UPNIHR As New MVPlantHour("UPNIHR")
    Private UPNPL As New MVPlantTime("UPNPL")
    Private UPNPLHR As New MVPlantHour("UPNPLHR")
    Private UPNPRIOR As New MVPlantHour("UPNPRIOR")
    Private WTBODY As New MVTime("WTBODY")
    Private WTBODYIN As Double
    Private WTCALF As New MVTime("WTCALF")
    Private WTCON As New MVTime("WTCON")
    Private WTEMPTY As New MVTime("WTEMPTY")
    Private WTFAT As New MVTime("WTFAT")
    Private WTFATCHG As New MVTime("WTFATCHG")
    Private WTFATMIN As New MVTime("WTFATMIN")
    Private WTFET As New MVTime("WTFET")
    Private WTFFIF As New MVTime("WTFFIF")
    Private WTGUT As New MVTime("WTGUT")
    Private WTMAT As New MVTime("WTMAT")
    Private WTMUS As New MVTime("WTMUS")
    Private WTPRO As New MVTime("WTPRO")
    Private WTPROCHG As New MVTime("WTPROCHG")
    Private WTPROMIN As New MVTime("WTPROMIN")
    Private WTRUM As New MVTime("WTRUM")
    Private WTRUMWET As New MVTime("WTRUMWET")
    Private WTWAT As New MVTime("WTWAT")
    Private WTWATFAT As New MVTime("WTWATFAT")
    Private WTWATMUS As New MVTime("WTWATMUS")
    Private PREGLAC_USERPREG As Boolean
    Private PREGLAC_USERWEAN As Boolean
    Private PREGLAC_THPREGWT As Double
    Private PREGLAC_THPCWTGN As Double
    Private PREGLAC_PSTD As Integer
    Private PREGLAC_PEND As Integer
    Private PREGLAC_POWEAND As Integer
    Private PREGLAC_THSPRTGN As Double
    Private PREGLAC_SSTD As Integer
    Private PREGLAC_SEND As Integer
    Private PREGLAC_SWEAND As Integer
    Private PREGLAC_THFMNCWT As New Double
    Private PREGLAC_FALLD As Integer
    Private PREGLAC_EAWEAND As Integer
    Private PREGLAC_NOWEAND As Integer
    Private BITESZADULT As Integer
    Private BITESZCOEF1 As Double
    Private BITESZCOEF2 As Double
    Private BITESZWTMOD As New MVTime("BITESZWTMOD")
    Private ACT_PEM_NOT_LACT As New Double
    Private ACT_PEM_NOT_PREGNANT As New Double


    'Temporary model variables used to read in data from a source and then pass it on to an 
    'instance variable ready to be used in equations
    'Used for all ModelVariables that are single values

    Private AGEIN As Integer
    Private CALFFATEIN As Integer
    Private DEBY As Double
    Private DECC As Double
    Private DECW As Double

    'IN_OTHER:
    Private mvAGEIN As New MVSingleValueOfInteger("AGE")
    Private mvBITESZADULT As New MVSingleValueOfInteger("BITESZADULT")
    Private mvBITESZCOEF1 As New MVSingleValueOfDouble("BITESZCOEF1")
    Private mvBITESZCOEF2 As New MVSingleValueOfDouble("BITESZCOEF2")
    Private mvCALFFATEIN As New MVSingleValueOfInteger("CALFFATE")
    Private mvDEBY As New MVSingleValueOfDouble("DEBY")
    Private mvDECC As New MVSingleValueOfDouble("DECC")
    Private mvDECW As New MVSingleValueOfDouble("DECW")
    Private mvEANTLCO As New MVSingleValueOfDouble("EANTLCO")
    Private mvEBMRCO As New MVSingleValueOfDouble("EBMRCO")
    Private mvECONCOAT As New MVSingleValueOfDouble("ECONCOAT")
    Private mvECONFAT As New MVSingleValueOfDouble("ECONFAT")
    Private mvECONFI As New MVSingleValueOfDouble("ECONFI")
    Private mvECONPRO As New MVSingleValueOfDouble("ECONPRO")
    Private mvENDAYAN As New MVSingleValueOfInteger("ENDAYAN")
    Private mvENDAYCT As New MVSingleValueOfInteger("ENDAYCT")
    Private mvENDAYGES As New MVSingleValueOfInteger("ENDAYGES")
    Private mvENDAYLAC As New MVSingleValueOfInteger("ENDAYLAC")
    Private mvENDAYSC As New MVSingleValueOfInteger("ENDAYSC")
    Private mvENDAYSUM As New MVSingleValueOfInteger("ENDAYSUM")
    Private mvESCRFCO As New MVSingleValueOfDouble("ESCRFCO")
    Private mvFATMOBRT As New MVSingleValueOfDouble("FATMOBRT")
    Private mvHREEAT As New MVSingleValueOfDouble("HREEAT")
    Private mvHRELIE As New MVSingleValueOfDouble("HRELIE")
    Private mvHREPAW As New MVSingleValueOfDouble("HREPAW")
    Private mvHRERUN As New MVSingleValueOfDouble("HRERUN")
    Private mvHRESTD As New MVSingleValueOfDouble("HRESTD")
    Private mvHREWLK As New MVSingleValueOfDouble("HREWLK")
    Private mvKPNDMIN As New MVSingleValueOfDouble("KPNDMIN")
    Private mvLACTIN As New MVSingleValueOfDouble("LACTIN")
    Private mvLACTYR As New MVSingleValueOfDouble("LACTYR")
    Private mvMFNCO As New MVSingleValueOfDouble("MFNCO")
    Private mvNANTLCO As New MVSingleValueOfDouble("NANTLCO")
    Private mvNCOATCO As New MVSingleValueOfDouble("NCOATCO")
    Private mvNCONPRO As New MVSingleValueOfDouble("NCONPRO")
    Private mvNEUNCO As New MVSingleValueOfDouble("NEUNCO")
    Private mvNFETCO As New MVSingleValueOfDouble("NFETCO")
    Private mvNSCRFCO As New MVSingleValueOfDouble("NSCRFCO")
    Private mvPBYN As New MVSingleValueOfDouble("PBYN")
    Private mvPCONFET As New MVSingleValueOfDouble("PCONFET")
    Private mvPCONIN As New MVSingleValueOfDouble("PCONIN")
    Private mvPCWN As New MVSingleValueOfDouble("PCWN")
    Private mvPDOM As New MVSingleValueOfDouble("PDOM")
    Private mvPDPN As New MVSingleValueOfDouble("PDPN")
    Private mvPFATDEP As New MVSingleValueOfDouble("PFATDEP")
    Private mvPFATIN As New MVSingleValueOfDouble("PFATIN")
    Private mvPFATMIN As New MVSingleValueOfDouble("PFATMIN")
    Private mvPFATWAT As New MVSingleValueOfDouble("PFATWAT")
    Private mvPFETFAT As New MVSingleValueOfDouble("PFETFAT")
    Private mvPMCDOM As New MVSingleValueOfDouble("PMCDOM")
    Private mvPMCN As New MVSingleValueOfDouble("PMCN")
    Private mvPMEBY As New MVSingleValueOfDouble("PMEBY")
    Private mvPMECC As New MVSingleValueOfDouble("PMECC")
    Private mvPMECW As New MVSingleValueOfDouble("PMECW")
    Private mvPMUSPRO As New MVSingleValueOfDouble("PMUSPRO")
    Private mvPMUSWAT As New MVSingleValueOfDouble("PMUSWAT")
    Private mvPPROIN As New MVSingleValueOfDouble("PPROIN")
    Private mvPPROMIN As New MVSingleValueOfDouble("PPROMIN")
    Private mvPRCAP As New MVSingleValueOfDouble("PRCAP")
    Private mvPREGIN As New MVSingleValueOfDouble("PREGIN")
    Private mvPREGYR As New MVSingleValueOfDouble("PREGYR")
    Private mvPROMOBRT As New MVSingleValueOfDouble("PROMOBRT")
    Private mvPRUMDRY As New MVSingleValueOfDouble("PRUMDRY")
    Private mvPRUMGUT As New MVSingleValueOfDouble("PRUMGUT")
    Private mvPTPCW_XMAX As New MVSingleValueOfDouble("PTPCW_XMAX")
    Private mvPTPCW_XMIN As New MVSingleValueOfDouble("PTPCW_XMIN")
    Private mvPTPCW_YMAX As New MVSingleValueOfDouble("PTPCW_YMAX")
    Private mvPTPCW_YMIN As New MVSingleValueOfDouble("PTPCW_YMIN")
    Private mvPTPNDIG As New MVSingleValueOfDouble("PTPNDIG")
    Private mvPUPN As New MVSingleValueOfDouble("PUPN")
    Private mvPWATIN As New MVSingleValueOfDouble("PWATIN")
    Private mvPWATMAX As New MVSingleValueOfDouble("PWATMAX")
    Private mvRNCCTAN_XMAX As New MVSingleValueOfDouble("RNCCTAN_XMAX")
    Private mvRNCCTAN_XMIN As New MVSingleValueOfDouble("RNCCTAN_XMIN")
    Private mvRNCCTAN_YMAX As New MVSingleValueOfDouble("RNCCTAN_YMAX")
    Private mvRNCCTAN_YMIN As New MVSingleValueOfDouble("RNCCTAN_YMIN")
    Private mvSDPROP As New MVSingleValueOfDouble("SDPROP")
    Private mvSTDAYAN As New MVSingleValueOfInteger("STDAYAN")
    Private mvSTDAYCT As New MVSingleValueOfInteger("STDAYCT")
    Private mvSTDAYGES As New MVSingleValueOfInteger("STDAYGES")
    Private mvSTDAYLAC As New MVSingleValueOfInteger("STDAYLAC")
    Private mvSTDAYSC As New MVSingleValueOfInteger("STDAYSC")
    Private mvSTDAYSUM As New MVSingleValueOfInteger("STDAYSUM")
    Private mvWTTBIR As New MVSingleValueOfDouble("WTTBIR")
    Private mvWTBODYIN As New MVSingleValueOfDouble("WTBODYIN")
    Private mvWTTMLKPR As New MVSingleValueOfDouble("WTTMLKPR")

    'IN_PREGLAC
    Private mvUSERPREG As New MVSingleValueOfInteger("USERPREG")
    Private mvUSERWEAN As New MVSingleValueOfInteger("USERWEAN")
    Private mvTHPREGWT As New MVSingleValueOfDouble("THPREGWT")
    Private mvTHPCWTGN As New MVSingleValueOfDouble("THPCWTGN")
    Private mvPSTD As New MVSingleValueOfInteger("PSTD")
    Private mvPEND As New MVSingleValueOfInteger("PEND")
    Private mvPOWEAND As New MVSingleValueOfInteger("POWEAND")
    Private mvTHSPRTGN As New MVSingleValueOfDouble("THSPRTGN")
    Private mvSSTD As New MVSingleValueOfInteger("SSTD")
    Private mvSEND As New MVSingleValueOfInteger("SEND")
    Private mvSWEAND As New MVSingleValueOfInteger("SWEAND")
    Private mvTHFMNCWT As New MVSingleValueOfDouble("THFMNCWT")
    Private mvFALLD As New MVSingleValueOfInteger("FALLD")
    Private mvEAWEAND As New MVSingleValueOfInteger("EAWEAND")
    Private mvNOWEAND As New MVSingleValueOfInteger("NOWEAND")

    ''' <summary>
    ''' Initialize ModelVariables at the start of a simulation
    ''' </summary>
    ''' <remarks></remarks>
    Private Sub InitializeModelVariables()
        'Dimension all of the ModelVariables to the default values for their ModelVariable type
        ' (no need to redimension ModelVariable0 variables)
        ABYFI.CreateDimensions()
        ACCDFI.CreateDimensions()
        ACCFI.CreateDimensions()
        ACCPOOL.CreateDimensions()
        ACWDFI.CreateDimensions()
        ACWFI.CreateDimensions()
        ACWPOOL.CreateDimensions()
        ADF.CreateDimensions()
        AFI.CreateDimensions()
        ANDFI.CreateDimensions()
        ANDPOOL.CreateDimensions()
        AR.CreateDimensions()
        ATPOOL.CreateDimensions()
        BITESZWTMOD.CreateDimensions()
        BSA.CreateDimensions()
        BYFEC.CreateDimensions()
        BYFECHR.CreateDimensions()
        BYFI.CreateDimensions()
        BYFIHR.CreateDimensions()
        BYMEI.CreateDimensions()
        BYMEIHR.CreateDimensions()
        BYMNI.CreateDimensions()
        BYMNIHR.CreateDimensions()
        BYNFEC.CreateDimensions()
        BYNFECHR.CreateDimensions()
        BYNI.CreateDimensions()
        BYNIHR.CreateDimensions()
        CCDFI.CreateDimensions()
        CCDFIHR.CreateDimensions()
        CCDNI.CreateDimensions()
        CCDNIHR.CreateDimensions()
        CCFEC.CreateDimensions()
        CCFECHR.CreateDimensions()
        CCMEI.CreateDimensions()
        CCMEIHR.CreateDimensions()
        CCMNI.CreateDimensions()
        CCMNIHR.CreateDimensions()
        CCNFEC.CreateDimensions()
        CCNFECHR.CreateDimensions()
        CCNI.CreateDimensions()
        CCNIHR.CreateDimensions()
        CCNPL.CreateDimensions()
        CCNPLHR.CreateDimensions()
        CCNPRIOR.CreateDimensions()
        CCPOOL.CreateDimensions()
        CCPOOLHR.CreateDimensions()
        CCPOOLIN.CreateDimensions()
        CCPRIOR.CreateDimensions()
        CWDFI.CreateDimensions()
        CWDFIHR.CreateDimensions()
        CWDNI.CreateDimensions()
        CWDNIHR.CreateDimensions()
        CWFEC.CreateDimensions()
        CWFECHR.CreateDimensions()
        CWMEI.CreateDimensions()
        CWMEIHR.CreateDimensions()
        CWMNI.CreateDimensions()
        CWMNIHR.CreateDimensions()
        CWNFEC.CreateDimensions()
        CWNDFECHR.CreateDimensions()
        CWNI.CreateDimensions()
        CWNIHR.CreateDimensions()
        CWNPL.CreateDimensions()
        CWNPLHR.CreateDimensions()
        CWNPRIOR.CreateDimensions()
        CWPOOL.CreateDimensions()
        CWPOOLHR.CreateDimensions()
        CWPOOLIN.CreateDimensions()
        CWPRIOR.CreateDimensions()
        AGEOUT.CreateDimensions()
        CALFFATEOUT.CreateDimensions()
        DAYSGES.CreateDimensions()
        DAYSLAC.CreateDimensions()
        DFI.CreateDimensions()
        DIET.CreateDimensions()
        DPMNI.CreateDimensions()
        DPMNIHR.CreateDimensions()
        DPNFEC.CreateDimensions()
        DPNFECHR.CreateDimensions()
        DPNI.CreateDimensions()
        DPNIHR.CreateDimensions()
        DPNPL.CreateDimensions()
        DPNPLHR.CreateDimensions()
        DPNPRIOR.CreateDimensions()
        DPNPRIOR.CreateDimensions()
        EA.CreateDimensions()
        EAFAT.CreateDimensions()
        EAINT.CreateDimensions()
        EAPRO.CreateDimensions()
        EAPRORE.CreateDimensions()
        EB.CreateDimensions()
        ECONMLK.CreateDimensions()
        EDFAT.CreateDimensions()
        EDPRO.CreateDimensions()
        EFATCHG.CreateDimensions()
        ER.CreateDimensions()
        ERACT.CreateDimensions()
        ERANTL.CreateDimensions()
        ERBASE.CreateDimensions()
        ERCOAT.CreateDimensions()
        EREAT.CreateDimensions()
        ERFAT.CreateDimensions()
        ERFDEP.CreateDimensions()
        ERFET.CreateDimensions()
        ERGES.CreateDimensions()
        ERGESFAT.CreateDimensions()
        ERINT.CreateDimensions()
        ERLAC.CreateDimensions()
        ERMA.CreateDimensions()
        ERMET.CreateDimensions()
        ERNP.CreateDimensions()
        ERPARA.CreateDimensions()
        ERPAW.CreateDimensions()
        ERPDEP.CreateDimensions()
        ERPRO.CreateDimensions()
        ERRUN.CreateDimensions()
        ERSCRF.CreateDimensions()
        ERSTD.CreateDimensions()
        ERSUM.CreateDimensions()
        ERTAR.CreateDimensions()
        ERWLK.CreateDimensions()
        EU.CreateDimensions()
        EUFAT.CreateDimensions()
        EUINT.CreateDimensions()
        EUN.CreateDimensions()
        EUPRO.CreateDimensions()
        EUPRORE.CreateDimensions()
        EXCEI.CreateDimensions()
        EXCEISUM.CreateDimensions()
        EXCFI.CreateDimensions()
        EXCFISUM.CreateDimensions()
        FATCAT.CreateDimensions()
        FATDEP.CreateDimensions()
        FB.CreateDimensions()
        FEC.CreateDimensions()
        FECHR.CreateDimensions()
        FECP.CreateDimensions()
        FI.CreateDimensions()
        FIHR.CreateDimensions()
        FIMET.CreateDimensions()
        FIP.CreateDimensions()
        FMMAX.CreateDimensions()
        HP.CreateDimensions()
        HPDFAT.CreateDimensions()
        HPDPRO.CreateDimensions()
        HPUFAT.CreateDimensions()
        HPUINT.CreateDimensions()
        HPUPRO.CreateDimensions()
        HPUPRORE.CreateDimensions()
        KEFAT.CreateDimensions()
        KEINT.CreateDimensions()
        KEPRO.CreateDimensions()
        KNINT.CreateDimensions()
        KNPRO.CreateDimensions()
        KPCC.CreateDimensions()
        KPCW.CreateDimensions()
        KPND.CreateDimensions()
        LACT.CreateDimensions()
        MAXSNODEP.CreateDimensions()
        MAXWTFET.CreateDimensions()
        MCDOMMX.CreateDimensions()
        MCDOMMXD.CreateDimensions()
        MCMNI.CreateDimensions()
        MCMNIHR.CreateDimensions()
        MCNFEC.CreateDimensions()
        MCNFECHR.CreateDimensions()
        MCNIMX.CreateDimensions()
        MCNIMXD.CreateDimensions()
        MCNPL.CreateDimensions()
        MCNPLHR.CreateDimensions()
        MCNPRIOR.CreateDimensions()
        MEI.CreateDimensions()
        MEIHR.CreateDimensions()
        MEIP.CreateDimensions()
        MFN.CreateDimensions()
        MNI.CreateDimensions()
        MNIHR.CreateDimensions()
        MNIP.CreateDimensions()
        MNL.CreateDimensions()
        MPFI.CreateDimensions()
        MPFIAVG.CreateDimensions()
        NA.CreateDimensions()
        NAINT.CreateDimensions()
        NAPRO.CreateDimensions()
        NAPRORE.CreateDimensions()
        NB.CreateDimensions()
        NDF.CreateDimensions()
        NDFEC.CreateDimensions()
        NDFECHR.CreateDimensions()
        NDFI.CreateDimensions()
        NDFIHR.CreateDimensions()
        NDNFEC.CreateDimensions()
        NDNFECHR.CreateDimensions()
        NDNI.CreateDimensions()
        NDNIHR.CreateDimensions()
        NDNPL.CreateDimensions()
        NDNPLHR.CreateDimensions()
        NDNPRIOR.CreateDimensions()
        NDPOOL.CreateDimensions()
        NDPOOLHR.CreateDimensions()
        NDPOOLIN.CreateDimensions()
        NDPRIOR.CreateDimensions()
        NDPRO.CreateDimensions()
        NFEC.CreateDimensions()
        NFECHR.CreateDimensions()
        NI.CreateDimensions()
        NIHR.CreateDimensions()
        NLDPRO.CreateDimensions()
        NLUINT.CreateDimensions()
        NLUPRO.CreateDimensions()
        NLUPRORE.CreateDimensions()
        NPNI.CreateDimensions()
        NPNIHR.CreateDimensions()
        NPNURN.CreateDimensions()
        NPNURNHR.CreateDimensions()
        NPROCHG.CreateDimensions()
        NR.CreateDimensions()
        NRACT.CreateDimensions()
        NRANTL.CreateDimensions()
        NRBASE.CreateDimensions()
        NRCOAT.CreateDimensions()
        NRFDEP.CreateDimensions()
        NRFET.CreateDimensions()
        NRGES.CreateDimensions()
        NRINT.CreateDimensions()
        NRLAC.CreateDimensions()
        NRMA.CreateDimensions()
        NRMET.CreateDimensions()
        NRPARA.CreateDimensions()
        NRPDEP.CreateDimensions()
        NRPRO.CreateDimensions()
        NRSCRF.CreateDimensions()
        NRSUM.CreateDimensions()
        NRTAR.CreateDimensions()
        NRUM.CreateDimensions()
        NU.CreateDimensions()
        NUINT.CreateDimensions()
        NUPRO.CreateDimensions()
        NUPRORE.CreateDimensions()
        PCC.CreateDimensions()
        PCCDIG.CreateDimensions()
        PCCDIGIN.CreateDimensions()
        PCCDNIBY.CreateDimensions()
        PCCIBY.CreateDimensions()
        PCMAX.CreateDimensions()
        PCONMLK.CreateDimensions()
        PCWDIG.CreateDimensions()
        PDEG.CreateDimensions()
        PDIG.CreateDimensions()
        PERTAR.CreateDimensions()
        PFAT.CreateDimensions()
        PFIP.CreateDimensions()
        PFOR.CreateDimensions()
        PFOREAT.CreateDimensions()
        PFORPAW.CreateDimensions()
        PLIE.CreateDimensions()
        PMCNI.CreateDimensions()
        PMCNIAVG.CreateDimensions()
        PMMAX.CreateDimensions()
        PNIT.CreateDimensions()
        PNRTAR.CreateDimensions()
        PPRO.CreateDimensions()
        PREG.CreateDimensions()
        PROCAT.CreateDimensions()
        PRODEP.CreateDimensions()
        PRTAR.CreateDimensions()
        PRUN.CreateDimensions()
        PSTD.CreateDimensions()
        PTARSUM.CreateDimensions()
        PTPCW.CreateDimensions()
        PWLK.CreateDimensions()
        QM.CreateDimensions()
        RBYFI.CreateDimensions()
        RCAP.CreateDimensions()
        RCCDFI.CreateDimensions()
        RCCPOOL.CreateDimensions()
        RCCTAN.CreateDimensions()
        RCWDFI.CreateDimensions()
        RCWPOOL.CreateDimensions()
        REI.CreateDimensions()
        RENBY.CreateDimensions()
        RENCC.CreateDimensions()
        RENCW.CreateDimensions()
        RNCCTAN.CreateDimensions()
        RNDFI.CreateDimensions()
        RPFI.CreateDimensions()
        RPFIAVG.CreateDimensions()
        SINKDEP.CreateDimensions()
        SNODEP.CreateDimensions()
        SNOWX.CreateDimensions()
        STAGEPR.CreateDimensions()
        LOCATION.CreateDimensions()
        TER.CreateDimensions()
        TGRCALF.CreateDimensions()
        TGRFET.CreateDimensions()
        TMLKPR.CreateDimensions()
        TMLKPRWT.CreateDimensions()
        TOTDIG.CreateDimensions()
        TPNI.CreateDimensions()
        TPNIHR.CreateDimensions()
        TWTCALF.CreateDimensions()
        TWTFET.CreateDimensions()
        UNL.CreateDimensions()
        UPMNI.CreateDimensions()
        UPMNIHR.CreateDimensions()
        UPNFEC.CreateDimensions()
        UPNFECHR.CreateDimensions()
        UPNI.CreateDimensions()
        UPNIHR.CreateDimensions()
        UPNPL.CreateDimensions()
        UPNPLHR.CreateDimensions()
        UPNPRIOR.CreateDimensions()
        WTBODY.CreateDimensions()
        WTCALF.CreateDimensions()
        WTCON.CreateDimensions()
        WTEMPTY.CreateDimensions()
        WTFAT.CreateDimensions()
        WTFATCHG.CreateDimensions()
        WTFATMIN.CreateDimensions()
        WTFET.CreateDimensions()
        WTFFIF.CreateDimensions()
        WTGUT.CreateDimensions()
        WTMAT.CreateDimensions()
        WTMUS.CreateDimensions()
        WTPRO.CreateDimensions()
        WTPROCHG.CreateDimensions()
        WTPROMIN.CreateDimensions()
        WTRUM.CreateDimensions()
        WTRUMWET.CreateDimensions()
        WTWAT.CreateDimensions()
        WTWATFAT.CreateDimensions()
        WTWATMUS.CreateDimensions()

        'Set the source for each model variable that is loaded from database
        Dim filterFieldNames() As String = {RunFieldName}   'Filter on Run ID for all source tables
        'IN_ACT
        PLIE.DataSource(dtIN_ACT, filterFieldNames)
        PSTD.DataSource(dtIN_ACT, filterFieldNames)
        PWLK.DataSource(dtIN_ACT, filterFieldNames)
        PRUN.DataSource(dtIN_ACT, filterFieldNames)
        PFOR.DataSource(dtIN_ACT, filterFieldNames)
        PFOREAT.DataSource(dtIN_ACT, filterFieldNames)
        PFORPAW.DataSource(dtIN_ACT, filterFieldNames)


        'IN_ADF
        ADF.DataSource(dtIN_ADF, filterFieldNames)

        'IN_AR()
        AR.DataSource(dtIN_AR, filterFieldNames)

        'IN_BSA
        BSA.DataSource(dtIN_BSA, filterFieldNames)

        'IN_DIET
        DIET.DataSource(dtIN_DIET, filterFieldNames)

        'IN_FB
        FB.DataSource(dtIN_FB, filterFieldNames)

        'IN_KP:
        KPCC.DataSource(dtIN_KP, filterFieldNames)
        KPCW.DataSource(dtIN_KP, filterFieldNames)

        'IN_NDF
        NDF.DataSource(dtIN_NDF, filterFieldNames)

        'IN_OTHER:
        'For ModelVariable0, set source to a temporary MV
        mvAGEIN.DataSource(dtIN_OTHER, filterFieldNames)
        mvBITESZADULT.DataSource(dtIN_OTHER, filterFieldNames)
        mvBITESZCOEF1.DataSource(dtIN_OTHER, filterFieldNames)
        mvBITESZCOEF2.DataSource(dtIN_OTHER, filterFieldNames)
        mvCALFFATEIN.DataSource(dtIN_OTHER, filterFieldNames)
        mvDEBY.DataSource(dtIN_OTHER, filterFieldNames)
        mvDECC.DataSource(dtIN_OTHER, filterFieldNames)
        mvDECW.DataSource(dtIN_OTHER, filterFieldNames)
        mvEANTLCO.DataSource(dtIN_OTHER, filterFieldNames)
        mvEBMRCO.DataSource(dtIN_OTHER, filterFieldNames)
        mvECONCOAT.DataSource(dtIN_OTHER, filterFieldNames)
        mvECONFAT.DataSource(dtIN_OTHER, filterFieldNames)
        mvECONFI.DataSource(dtIN_OTHER, filterFieldNames)
        mvECONPRO.DataSource(dtIN_OTHER, filterFieldNames)
        mvENDAYAN.DataSource(dtIN_OTHER, filterFieldNames)
        mvENDAYCT.DataSource(dtIN_OTHER, filterFieldNames)
        mvENDAYGES.DataSource(dtIN_OTHER, filterFieldNames)
        mvENDAYLAC.DataSource(dtIN_OTHER, filterFieldNames)
        mvENDAYSC.DataSource(dtIN_OTHER, filterFieldNames)
        mvENDAYSUM.DataSource(dtIN_OTHER, filterFieldNames)
        mvESCRFCO.DataSource(dtIN_OTHER, filterFieldNames)
        mvFATMOBRT.DataSource(dtIN_OTHER, filterFieldNames)
        mvHREEAT.DataSource(dtIN_OTHER, filterFieldNames)
        mvHRELIE.DataSource(dtIN_OTHER, filterFieldNames)
        mvHREPAW.DataSource(dtIN_OTHER, filterFieldNames)
        mvHRERUN.DataSource(dtIN_OTHER, filterFieldNames)
        mvHRESTD.DataSource(dtIN_OTHER, filterFieldNames)
        mvHREWLK.DataSource(dtIN_OTHER, filterFieldNames)
        mvKPNDMIN.DataSource(dtIN_OTHER, filterFieldNames)
        mvLACTIN.DataSource(dtIN_OTHER, filterFieldNames)
        mvLACTYR.DataSource(dtIN_OTHER, filterFieldNames)
        mvMFNCO.DataSource(dtIN_OTHER, filterFieldNames)
        mvNANTLCO.DataSource(dtIN_OTHER, filterFieldNames)
        mvNCOATCO.DataSource(dtIN_OTHER, filterFieldNames)
        mvNCONPRO.DataSource(dtIN_OTHER, filterFieldNames)
        mvNEUNCO.DataSource(dtIN_OTHER, filterFieldNames)
        mvNFETCO.DataSource(dtIN_OTHER, filterFieldNames)
        mvNSCRFCO.DataSource(dtIN_OTHER, filterFieldNames)
        mvPBYN.DataSource(dtIN_OTHER, filterFieldNames)
        mvPCONFET.DataSource(dtIN_OTHER, filterFieldNames)
        mvPCONIN.DataSource(dtIN_OTHER, filterFieldNames)
        mvPCWN.DataSource(dtIN_OTHER, filterFieldNames)
        mvPDOM.DataSource(dtIN_OTHER, filterFieldNames)
        mvPDPN.DataSource(dtIN_OTHER, filterFieldNames)
        mvPFATDEP.DataSource(dtIN_OTHER, filterFieldNames)
        mvPFATMIN.DataSource(dtIN_OTHER, filterFieldNames)
        mvPFATWAT.DataSource(dtIN_OTHER, filterFieldNames)
        mvPFETFAT.DataSource(dtIN_OTHER, filterFieldNames)
        mvPMCDOM.DataSource(dtIN_OTHER, filterFieldNames)
        mvPMCN.DataSource(dtIN_OTHER, filterFieldNames)
        mvPMEBY.DataSource(dtIN_OTHER, filterFieldNames)
        mvPMECC.DataSource(dtIN_OTHER, filterFieldNames)
        mvPMECW.DataSource(dtIN_OTHER, filterFieldNames)
        mvPMUSPRO.DataSource(dtIN_OTHER, filterFieldNames)
        mvPMUSWAT.DataSource(dtIN_OTHER, filterFieldNames)
        mvPPROMIN.DataSource(dtIN_OTHER, filterFieldNames)
        mvPRCAP.DataSource(dtIN_OTHER, filterFieldNames)
        mvPREGIN.DataSource(dtIN_OTHER, filterFieldNames)
        mvPREGYR.DataSource(dtIN_OTHER, filterFieldNames)
        mvPROMOBRT.DataSource(dtIN_OTHER, filterFieldNames)
        mvPRUMDRY.DataSource(dtIN_OTHER, filterFieldNames)
        mvPRUMGUT.DataSource(dtIN_OTHER, filterFieldNames)
        mvPTPCW_XMAX.DataSource(dtIN_OTHER, filterFieldNames)
        mvPTPCW_XMIN.DataSource(dtIN_OTHER, filterFieldNames)
        mvPTPCW_YMAX.DataSource(dtIN_OTHER, filterFieldNames)
        mvPTPCW_YMIN.DataSource(dtIN_OTHER, filterFieldNames)
        mvPTPNDIG.DataSource(dtIN_OTHER, filterFieldNames)
        mvPUPN.DataSource(dtIN_OTHER, filterFieldNames)
        mvPWATIN.DataSource(dtIN_OTHER, filterFieldNames)
        mvPWATMAX.DataSource(dtIN_OTHER, filterFieldNames)
        mvPFATIN.DataSource(dtIN_OTHER, filterFieldNames)
        mvPPROIN.DataSource(dtIN_OTHER, filterFieldNames)
        mvRNCCTAN_XMAX.DataSource(dtIN_OTHER, filterFieldNames)
        mvRNCCTAN_XMIN.DataSource(dtIN_OTHER, filterFieldNames)
        mvRNCCTAN_YMAX.DataSource(dtIN_OTHER, filterFieldNames)
        mvRNCCTAN_YMIN.DataSource(dtIN_OTHER, filterFieldNames)
        mvSDPROP.DataSource(dtIN_OTHER, filterFieldNames)
        mvSTDAYAN.DataSource(dtIN_OTHER, filterFieldNames)
        mvSTDAYCT.DataSource(dtIN_OTHER, filterFieldNames)
        mvSTDAYGES.DataSource(dtIN_OTHER, filterFieldNames)
        mvSTDAYLAC.DataSource(dtIN_OTHER, filterFieldNames)
        mvSTDAYSC.DataSource(dtIN_OTHER, filterFieldNames)
        mvSTDAYSUM.DataSource(dtIN_OTHER, filterFieldNames)
        mvWTBODYIN.DataSource(dtIN_OTHER, filterFieldNames)
        mvWTTBIR.DataSource(dtIN_OTHER, filterFieldNames)
        mvWTTMLKPR.DataSource(dtIN_OTHER, filterFieldNames)

        'IN_PREGLAC
        mvUSERPREG.DataSource(dtIN_PREGLAC, filterFieldNames)
        mvUSERWEAN.DataSource(dtIN_PREGLAC, filterFieldNames)
        mvTHPREGWT.DataSource(dtIN_PREGLAC, filterFieldNames)
        mvTHPCWTGN.DataSource(dtIN_PREGLAC, filterFieldNames)
        mvPSTD.DataSource(dtIN_PREGLAC, filterFieldNames)
        mvPEND.DataSource(dtIN_PREGLAC, filterFieldNames)
        mvPOWEAND.DataSource(dtIN_PREGLAC, filterFieldNames)
        mvTHSPRTGN.DataSource(dtIN_PREGLAC, filterFieldNames)
        mvSSTD.DataSource(dtIN_PREGLAC, filterFieldNames)
        mvSEND.DataSource(dtIN_PREGLAC, filterFieldNames)
        mvSWEAND.DataSource(dtIN_PREGLAC, filterFieldNames)
        mvTHFMNCWT.DataSource(dtIN_PREGLAC, filterFieldNames)
        mvFALLD.DataSource(dtIN_PREGLAC, filterFieldNames)
        mvEAWEAND.DataSource(dtIN_PREGLAC, filterFieldNames)
        mvNOWEAND.DataSource(dtIN_PREGLAC, filterFieldNames)

        'IN_PARA:
        NRPARA.DataSource(dtIN_PARA, filterFieldNames)
        ERPARA.DataSource(dtIN_PARA, filterFieldNames)

        'IN_PCCIBY:
        PCCIBY.DataSource(dtIN_PCCIBY, filterFieldNames)

        'IN_PCMAX
        PCMAX.DataSource(dtIN_PCMAX, filterFieldNames)

        'IN_PDEG
        PDEG.DataSource(dtIN_PDEG, filterFieldNames)

        'IN_PNIT
        PNIT.DataSource(dtIN_PNIT, filterFieldNames)

        'IN_PTARSUM:
        PTARSUM.DataSource(dtIN_PTARSUM, filterFieldNames)

        'IN_RUMEN()
        CCPOOLIN.DataSource(dtIN_RUMEN, filterFieldNames)
        CWPOOLIN.DataSource(dtIN_RUMEN, filterFieldNames)
        NDPOOLIN.DataSource(dtIN_RUMEN, filterFieldNames)

        'IN_SNODEP:
        SNODEP.DataSource(dtIN_SNODEP, filterFieldNames)

        'IN_STAGE:
        KEFAT.DataSource(dtIN_STAGE, filterFieldNames)
        KEINT.DataSource(dtIN_STAGE, filterFieldNames)
        KEPRO.DataSource(dtIN_STAGE, filterFieldNames)
        KNINT.DataSource(dtIN_STAGE, filterFieldNames)
        KNPRO.DataSource(dtIN_STAGE, filterFieldNames)

        'IN_STRATUM:
        LOCATION.DataSource(dtIN_LOCATION, filterFieldNames)

    End Sub

    Private Sub LoadModelVariables(ByVal nRun As Integer)

        Dim filterValues() As Integer = {nRun}   'Filter for the correct run when loading source data

        'Load data from source database tables, filtered as required
        'Assumes that each ModelVariable has been initialized (ie datatable and field names already set)
        'ModelVariables requiring additional processing are first loaded into a temporary ModelVariable

        PLIE.Load(filterValues)
        PSTD.Load(filterValues)
        PWLK.Load(filterValues)
        PRUN.Load(filterValues)
        PFOR.Load(filterValues)
        PFOREAT.Load(filterValues)
        PFORPAW.Load(filterValues)
        ADF.Load(filterValues)
        AR.Load(filterValues)
        BSA.Load(filterValues)
        DIET.Load(filterValues)
        FB.Load(filterValues)
        KPCC.Load(filterValues)
        KPCW.Load(filterValues)
        NDF.Load(filterValues)
        mvAGEIN.Load(filterValues)
        mvBITESZADULT.Load(filterValues)
        mvBITESZCOEF1.Load(filterValues)
        mvBITESZCOEF2.Load(filterValues)
        mvCALFFATEIN.Load(filterValues)
        mvDEBY.Load(filterValues)
        mvDECC.Load(filterValues)
        mvDECW.Load(filterValues)
        mvEANTLCO.Load(filterValues)
        mvEBMRCO.Load(filterValues)
        mvECONCOAT.Load(filterValues)
        mvECONFAT.Load(filterValues)
        mvECONFI.Load(filterValues)
        mvECONPRO.Load(filterValues)
        mvENDAYAN.Load(filterValues)
        mvENDAYCT.Load(filterValues)
        mvENDAYGES.Load(filterValues)
        mvENDAYLAC.Load(filterValues)
        mvENDAYSC.Load(filterValues)
        mvENDAYSUM.Load(filterValues)
        mvESCRFCO.Load(filterValues)
        mvFATMOBRT.Load(filterValues)
        mvHREEAT.Load(filterValues)
        mvHRELIE.Load(filterValues)
        mvHREPAW.Load(filterValues)
        mvHRERUN.Load(filterValues)
        mvHRESTD.Load(filterValues)
        mvHREWLK.Load(filterValues)
        mvKPNDMIN.Load(filterValues)
        mvLACTIN.Load(filterValues)
        mvLACTYR.Load(filterValues)
        mvMFNCO.Load(filterValues)
        mvNANTLCO.Load(filterValues)
        mvNCOATCO.Load(filterValues)
        mvNCONPRO.Load(filterValues)
        mvNEUNCO.Load(filterValues)
        mvNFETCO.Load(filterValues)
        mvNSCRFCO.Load(filterValues)
        mvPBYN.Load(filterValues)
        mvPCONFET.Load(filterValues)
        mvPCONIN.Load(filterValues)
        mvPCWN.Load(filterValues)
        mvPDOM.Load(filterValues)
        mvPDPN.Load(filterValues)
        mvPFATDEP.Load(filterValues)
        mvPFATMIN.Load(filterValues)
        mvPFATWAT.Load(filterValues)
        mvPFETFAT.Load(filterValues)
        mvPMCDOM.Load(filterValues)
        mvPMCN.Load(filterValues)
        mvPMEBY.Load(filterValues)
        mvPMECC.Load(filterValues)
        mvPMECW.Load(filterValues)
        mvPMUSPRO.Load(filterValues)
        mvPMUSWAT.Load(filterValues)
        mvPPROMIN.Load(filterValues)
        mvPRCAP.Load(filterValues)
        mvPREGIN.Load(filterValues)
        mvPREGYR.Load(filterValues)
        mvPROMOBRT.Load(filterValues)
        mvPRUMDRY.Load(filterValues)
        mvPRUMGUT.Load(filterValues)
        mvPTPCW_XMAX.Load(filterValues)
        mvPTPCW_XMIN.Load(filterValues)
        mvPTPCW_YMAX.Load(filterValues)
        mvPTPCW_YMIN.Load(filterValues)
        mvPTPNDIG.Load(filterValues)
        mvPUPN.Load(filterValues)
        mvPWATIN.Load(filterValues)
        mvPWATMAX.Load(filterValues)
        mvPFATIN.Load(filterValues)
        mvPPROIN.Load(filterValues)
        mvRNCCTAN_XMAX.Load(filterValues)
        mvRNCCTAN_XMIN.Load(filterValues)
        mvRNCCTAN_YMAX.Load(filterValues)
        mvRNCCTAN_YMIN.Load(filterValues)
        mvSDPROP.Load(filterValues)
        mvSTDAYAN.Load(filterValues)
        mvSTDAYCT.Load(filterValues)
        mvSTDAYGES.Load(filterValues)
        mvSTDAYLAC.Load(filterValues)
        mvSTDAYSC.Load(filterValues)
        mvSTDAYSUM.Load(filterValues)
        mvWTBODYIN.Load(filterValues)
        mvWTTBIR.Load(filterValues)
        mvWTTMLKPR.Load(filterValues)
        mvUSERPREG.Load(filterValues)
        mvUSERWEAN.Load(filterValues)
        mvTHPREGWT.Load(filterValues)
        mvTHPCWTGN.Load(filterValues)
        mvPSTD.Load(filterValues)
        mvPEND.Load(filterValues)
        mvPOWEAND.Load(filterValues)
        mvTHSPRTGN.Load(filterValues)
        mvSSTD.Load(filterValues)
        mvSEND.Load(filterValues)
        mvSWEAND.Load(filterValues)
        mvTHFMNCWT.Load(filterValues)
        mvFALLD.Load(filterValues)
        mvEAWEAND.Load(filterValues)
        mvNOWEAND.Load(filterValues)
        NRPARA.Load(filterValues)
        ERPARA.Load(filterValues)
        PCCIBY.Load(filterValues)
        PCMAX.Load(filterValues)
        PDEG.Load(filterValues)
        PNIT.Load(filterValues)
        PTARSUM.Load(filterValues)
        CCPOOLIN.Load(filterValues)
        CWPOOLIN.Load(filterValues)
        NDPOOLIN.Load(filterValues)
        SNODEP.Load(filterValues)
        KEFAT.Load(filterValues)
        KEINT.Load(filterValues)
        KEPRO.Load(filterValues)
        KNINT.Load(filterValues)
        KNPRO.Load(filterValues)
        LOCATION.Load(filterValues)

        'For ModelVariable0 variables, copy to a regular variable
        AGEIN = mvAGEIN(0)
        BITESZADULT = mvBITESZADULT(0)
        BITESZCOEF1 = mvBITESZCOEF1(0)
        BITESZCOEF2 = mvBITESZCOEF2(0)
        CALFFATEIN = mvCALFFATEIN(0)
        DEBY = mvDEBY(0)
        DECC = mvDECC(0)
        DECW = mvDECW(0)
        EANTLCO = mvEANTLCO(0)
        EBMRCO = mvEBMRCO(0)
        ECONCOAT = mvECONCOAT(0)
        ECONFAT = mvECONFAT(0)
        ECONFI = mvECONFI(0)
        ECONPRO = mvECONPRO(0)
        ENDAYAN = mvENDAYAN(0)
        ENDAYCT = mvENDAYCT(0)
        ENDAYGES = mvENDAYGES(0)
        ENDAYLAC = mvENDAYLAC(0)
        ENDAYSC = mvENDAYSC(0)
        ENDAYSUM = mvENDAYSUM(0)
        ESCRFCO = mvESCRFCO(0)
        FATMOBRT = mvFATMOBRT(0)
        HREEAT = mvHREEAT(0)
        HRELIE = mvHRELIE(0)
        HREPAW = mvHREPAW(0)
        HRERUN = mvHRERUN(0)
        HRESTD = mvHRESTD(0)
        HREWLK = mvHREWLK(0)
        KPNDMIN = mvKPNDMIN(0)
        LACTIN = mvLACTIN(0)
        LACTYR = mvLACTYR(0)
        MFNCO = mvMFNCO(0)
        NANTLCO = mvNANTLCO(0)
        NCOATCO = mvNCOATCO(0)
        NCONPRO = mvNCONPRO(0)
        NEUNCO = mvNEUNCO(0)
        NFETCO = mvNFETCO(0)
        NSCRFCO = mvNSCRFCO(0)
        PBYN = mvPBYN(0)
        PCONFET = mvPCONFET(0)
        PCONIN = mvPCONIN(0)
        PCWN = mvPCWN(0)
        PDOM = mvPDOM(0)
        PDPN = mvPDPN(0)
        PFATDEP = mvPFATDEP(0)
        PFATMIN = mvPFATMIN(0)
        PFATWAT = mvPFATWAT(0)
        PFETFAT = mvPFETFAT(0)
        PMCDOM = mvPMCDOM(0)
        PMCN = mvPMCN(0)
        PMEBY = mvPMEBY(0)
        PMECC = mvPMECC(0)
        PMECW = mvPMECW(0)
        PMUSPRO = mvPMUSPRO(0)
        PMUSWAT = mvPMUSWAT(0)
        PPROMIN = mvPPROMIN(0)
        PRCAP = mvPRCAP(0)
        PREGIN = mvPREGIN(0)
        PREGYR = mvPREGYR(0)
        PROMOBRT = mvPROMOBRT(0)
        PRUMDRY = mvPRUMDRY(0)
        PRUMGUT = mvPRUMGUT(0)
        PTPCW_XMAX = mvPTPCW_XMAX(0)
        PTPCW_XMIN = mvPTPCW_XMIN(0)
        PTPCW_YMAX = mvPTPCW_YMAX(0)
        PTPCW_YMIN = mvPTPCW_YMIN(0)
        PTPNDIG = mvPTPNDIG(0)
        PUPN = mvPUPN(0)
        PWATIN = mvPWATIN(0)
        PWATMAX = mvPWATMAX(0)
        PFATIN = mvPFATIN(0)
        PPROIN = mvPPROIN(0)
        RNCCTAN_XMAX = mvRNCCTAN_XMAX(0)
        RNCCTAN_XMIN = mvRNCCTAN_XMIN(0)
        RNCCTAN_YMAX = mvRNCCTAN_YMAX(0)
        RNCCTAN_YMIN = mvRNCCTAN_YMIN(0)
        SDPROP = mvSDPROP(0)
        STDAYAN = mvSTDAYAN(0)
        STDAYCT = mvSTDAYCT(0)
        STDAYGES = mvSTDAYGES(0)
        STDAYLAC = mvSTDAYLAC(0)
        STDAYSC = mvSTDAYSC(0)
        STDAYSUM = mvSTDAYSUM(0)
        WTBODYIN = mvWTBODYIN(0)
        WTTBIR = mvWTTBIR(0)
        WTTMLKPR = mvWTTMLKPR(0)

        PREGLAC_USERPREG = CBool(mvUSERPREG(0))
        PREGLAC_USERWEAN = CBool(mvUSERWEAN(0))
        PREGLAC_THPREGWT = mvTHPREGWT(0)
        PREGLAC_THPCWTGN = mvTHPCWTGN(0)
        PREGLAC_PSTD = mvPSTD(0)
        PREGLAC_PEND = mvPEND(0)
        PREGLAC_POWEAND = mvPOWEAND(0)
        PREGLAC_THSPRTGN = mvTHSPRTGN(0)
        PREGLAC_SSTD = mvSSTD(0)
        PREGLAC_SEND = mvSEND(0)
        PREGLAC_SWEAND = mvSWEAND(0)
        PREGLAC_THFMNCWT = mvTHFMNCWT(0)
        PREGLAC_FALLD = mvFALLD(0)
        PREGLAC_EAWEAND = mvEAWEAND(0)
        PREGLAC_NOWEAND = mvNOWEAND(0)

        'Check for individual null values
        ACT_PEM_NOT_LACT = 1.0
        ACT_PEM_NOT_PREGNANT = 1.0
        If Me.dtIN_ACT_PEM.Rows.Count > 0 Then
            Dim dr As DataRow = Me.dtIN_ACT_PEM.Rows(0)
            If Not (dr("NotLactating") Is DBNull.Value) Then
                ACT_PEM_NOT_LACT = dr("NotLactating")
            End If

            If Not (dr("NotPregnant") Is DBNull.Value) Then
                ACT_PEM_NOT_PREGNANT = dr("NotPregnant")
            End If

        End If


        'Special case:  If there is no data for IN_PREGLAC, then USERWEAN and USERPREG should be set to True
        Dim query As String = String.Format("Iteration = {0}", nRun)
        Dim rows() As DataRow = Me.dtIN_PREGLAC.Select(query)
        Debug.Assert(rows.Count = 0 Or rows.Count = 1)

        If (rows.Count = 0) Then
            PREGLAC_USERPREG = True
            PREGLAC_USERWEAN = True
        End If

    End Sub

End Class
